# Generated by Django 4.2.7 on 2023-11-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Air_orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='小票序号')),
                ('hbl_num', models.CharField(max_length=64, null=True, verbose_name='HBL号')),
                ('big_ticket_id', models.IntegerField(verbose_name='大票ID')),
                ('hbl_status', models.CharField(max_length=2, verbose_name='HBL状态')),
                ('crate_date', models.DateField(blank=True, max_length=64, verbose_name='创建日期')),
                ('hbl_remake', models.CharField(max_length=200, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Air_track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='小票序号')),
                ('hbl_id', models.CharField(max_length=64, null=True, verbose_name='HBL号id')),
                ('track_status', models.CharField(max_length=2, verbose_name='HBL状态')),
                ('crate_date', models.DateField(blank=True, max_length=64, verbose_name='创建日期')),
                ('track_remake', models.CharField(max_length=200, verbose_name='备注')),
                ('status_display', models.IntegerField(default=0, verbose_name='是否显示')),
            ],
        ),
        migrations.CreateModel(
            name='Big_ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='大票序号')),
                ('big_ticket_num', models.CharField(max_length=64, null=True, verbose_name='大票号')),
                ('btg_cket_status', models.CharField(max_length=2, verbose_name='HBL状态')),
                ('crate_date', models.DateField(blank=True, max_length=64, verbose_name='创建日期')),
                ('hbl_remake', models.CharField(max_length=200, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='LmsUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('mobile', models.IntegerField(verbose_name='手机')),
            ],
        ),
    ]
