# Generated by Django 4.2.7 on 2023-11-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air_track',
            name='hbl_id',
            field=models.CharField(max_length=64, null=True, verbose_name='HBL号Id'),
        ),
    ]
