# Generated by Django 4.2.5 on 2023-12-07 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('air_app', '0003_delete_lmsuser_alter_air_orders_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air_orders',
            name='big_ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_app.big_ticket'),
        ),
        migrations.AlterField(
            model_name='air_orders',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='air_orders',
            name='hbl_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='air_orders',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='air_track',
            name='hbl_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_app.air_orders'),
        ),
        migrations.AlterField(
            model_name='air_track',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='air_track',
            name='update_date',
            field=models.DateField(auto_now=True, verbose_name='最后更新日期'),
        ),
        migrations.AlterField(
            model_name='air_track',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='big_ticket',
            name='big_ticket_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='big_ticket',
            name='crate_date',
            field=models.DateField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='big_ticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
