# Generated by Django 4.2.5 on 2023-12-07 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('air_app', '0004_alter_air_orders_big_ticket_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air_orders',
            name='big_ticket_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='air_app.big_ticket'),
        ),
        migrations.AlterField(
            model_name='air_orders',
            name='hbl_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='air_track',
            name='hbl_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='air_app.air_orders'),
        ),
        migrations.AlterField(
            model_name='air_track',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
