# Generated by Django 4.2.5 on 2023-12-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_app', '0005_alter_air_orders_big_ticket_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='air_orders',
            old_name='big_ticket_id',
            new_name='big_ticket',
        ),
        migrations.RenameField(
            model_name='air_track',
            old_name='hbl_id',
            new_name='hbl',
        ),
    ]
